# os x dev setup
# requirements: git, brew, brew-cask
---
- hosts: local

  pre_tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
      when: ansible_facts['os_family']|lower == 'darwin'

  roles:
    - role: install_packages
      tags:
        - install_packages
    - role: install_zsh
      tags:
        - install_zsh
    - role: install_git
      tags:
        - install_git
    - role: install_tmux
      tags:
        - install_tmux
    #- role: install_vim
    #tags:
      #- install_vim
      #- install_neovim
    - role: install_neovim
      tags:
        - install_neovim

