local_home: "{{ lookup('env','HOME') }}"
packages:
  - neovim
config_dirs:
  - "{{ local_home }}/.config/nvim"
config_links:
  - target: "{{ role_path }}/files/init.lua"
    link: "{{ local_home }}/.config/nvim/init.lua"

