packages:
  - awscli
  - azure-cli
  - ccls
  - cmake
  - coreutils
  - ctags
  - cscope
  - fzf
  - gettext
  - ipmitool
  - jq
  - libevent
  - libffi
  - libyaml
  - llvm
  - ncurses
  - nmap
  - openssl
  - pyenv
  - pyenv-virtualenv
  - readline
  - reattach-to-user-namespace
  - screenfetch
  - shellcheck
  - sshpass
  - tree
  - wget
  - yarn
  - zstd
  - htop
  - curl
  - rsync
  - kdiff3
  - the_silver_searcher

